name: Backend CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Make mvnw executable
      run: chmod +x ./mvnw
        
    - name: Run tests
      run: ./mvnw clean test
      
    - name: List test reports (debug)
      run: |
        echo "Checking for surefire reports..."
        ls -la target/surefire-reports/ || echo "No surefire-reports directory found"
        find target -name "TEST-*.xml" -type f || echo "No TEST-*.xml files found"
      
    - name: Build and package application
      run: ./mvnw clean compile package -DskipTests
      
    - name: Verify JAR file
      run: |
        echo "Checking for generated JAR files..."
        ls -la target/*.jar || echo "No JAR files found"
