name: Backend CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Make mvnw executable
      run: chmod +x ./mvnw
        
    - name: Run tests
      run: ./mvnw clean test
      
    - name: List test reports (debug)
      run: |
        echo "Checking for surefire reports..."
        ls -la target/surefire-reports/ || echo "No surefire-reports directory found"
        find target -name "TEST-*.xml" -type f || echo "No TEST-*.xml files found"
        
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: 'target/surefire-reports/TEST-*.xml'
        reporter: java-junit
        fail-on-error: false
        only-summary: false
      
    - name: Build and package application
      run: ./mvnw clean compile package -DskipTests
      
    - name: Verify JAR file
      run: |
        echo "Checking for generated JAR files..."
        ls -la target/*.jar || echo "No JAR files found"
        
    - name: Run integration tests (if any)
      run: ./mvnw verify -Pintegration-test
      continue-on-error: true
      
    - name: Generate build artifacts info
      run: |
        echo "Build completed successfully!"
        echo "Generated artifacts:"
        find target -name "*.jar" -type f
        echo "Build timestamp: $(date)"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: jar-artifacts
        path: target/*.jar
        retention-days: 30
        
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: target/surefire-reports/
        retention-days: 30

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Make mvnw executable
      run: chmod +x ./mvnw
        
    - name: Build production JAR
      run: ./mvnw clean package -DskipTests
      
    - name: Build Docker image
      run: |
        if [ -f Dockerfile ]; then
          docker build -t uiar-backend:latest .
          echo "Docker image built successfully"
        else
          echo "No Dockerfile found, skipping Docker build"
        fi
        
    - name: Prepare deployment artifacts
      run: |
        mkdir -p deployment-artifacts
        cp target/*.jar deployment-artifacts/ 2>/dev/null || echo "No JAR files to copy"
        echo "Deployment artifacts prepared"
        ls -la deployment-artifacts/
        
    - name: Upload deployment artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deployment-artifacts
        path: deployment-artifacts/
        retention-days: 90
